
## appendix_2 

#extracting data from toffolo 2014 and 2016 

```{r data_from_toffolo_2014, echo=FALSE, cache=TRUE}

# Toffolo 2014  -----------------------------------------------------------

toffolo_2014_df <- data.frame(
  study = c(2014, 2014, 2014, 2014),
  oc_group = c("high", "high", "low", "low"),
  target_present = c("absent", "present", "absent", "present"),
  mean_sec = c(6.05, 3.78, 5.66, 3.64),
  sd = c(1.38, 0.84, 1.3, 0.74),
  participants = c(55, 55, 56, 56),  # number of participants
  repetitions = c(25, 25, 25, 25)  # number of repetitions
  )

#computing SEM column 
toffolo_2014_df$sem <- toffolo_2014_df$sd / sqrt(toffolo_2014_df$participants)


# Transforming seconds to milliseconds
toffolo_2014_df$mean_ms <- toffolo_2014_df$mean_sec * 1000
toffolo_2014_df$sd_ms <- toffolo_2014_df$sd * 1000
toffolo_2014_df$sem_ms <- toffolo_2014_df$sem * 1000


# plotting figure 
ggplot(toffolo_2014_df, aes(x = target_present, y = mean_ms, group = oc_group, shape = oc_group)) +
  geom_point(position = position_dodge(0.9), size = 5) +
  geom_errorbar(aes(ymin = mean_ms - sem_ms, ymax = mean_ms + sem_ms),
                width = 0.4,
                position = position_dodge(0.9)) +
  scale_shape_manual(values = c("high" = 1, "low" = 2)) +
  scale_x_discrete(labels = c("absent" = "Absent", "present" = "Present")) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        text = element_text(size = 12)) +
  ylab('Mean RT (ms)') +
  labs(shape = "OC group") + 
  coord_cartesian(ylim = c(3000,7500))

ggsave(filename = "toffolo_2014_results.png",width = 4, height = 3, dpi = 1500)  

# Toffolo 2016 ------------------------------------------------------------

toffolo_2016_df <- data.frame(
  study = rep(2016, 6),
  oc_group = c("high", "high", "hc", "hc", "anx", "anx"),
  target_present = c("absent", "present", "absent", "present", "absent", "present"),
  mean_sec = c(8.55, 4.72, 6.86, 4.16, 7.21, 4.33),
  sd = c(3, 1.38, 1.69, 0.95, 2, 0.9),
  participants = c(31, 31, 31, 31, 26,26),  # number of participants
  repetitions = c(25, 25, 25, 25, 25,25)  # number of repetitions
)

#computing SEM column 
toffolo_2016_df$sem <- toffolo_2016_df$sd / sqrt(toffolo_2016_df$participants)


# Transforming seconds to milliseconds
toffolo_2016_df$mean_ms <- toffolo_2016_df$mean_sec * 1000
toffolo_2016_df$sd_ms <- toffolo_2016_df$sd * 1000
toffolo_2016_df$sem_ms <- toffolo_2016_df$sem * 1000

#plotting figure 

toffolo_2016_df %>% filter(oc_group!='anx') %>% 
  mutate(oc_group = factor(oc_group, levels = c("high","hc"))) %>% 

ggplot(aes(x = target_present, y = mean_ms, group = oc_group, shape = oc_group)) +
  geom_point(position = position_dodge(0.9), size = 5) +
  geom_errorbar(aes(ymin = mean_ms - sem_ms, ymax = mean_ms + sem_ms),
                width = 0.4,
                position = position_dodge(0.9)) +
  scale_shape_manual(values = c("high" = 1, "hc" = 2)) +
  scale_x_discrete(labels = c("absent" = "Absent", "present" = "Present")) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        text = element_text(size = 12)) +
  ylab('Mean RT (ms)') +
  labs(shape = "OC group") + 
  coord_cartesian(ylim = c(2000,9000))


ggsave(filename = "toffolo_2016_results.png",width = 4, height = 3, dpi = 1500)  

